# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: engage@kbase.us
author_name: KBase
has_binder: false
has_settings: false
kind: frontend
labextension_name: cdm-tree-browser
project_short_description: A JupyterLab extension for browsing file/data trees in
    KBase CDM JupyterLab.
python_name: cdm_tree_browser
repository: https://github.com/kbaseincubator/cdm-tree-browser
test: true

